cmake_minimum_required(VERSION 3.16)
project(oop_project LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Threads REQUIRED)
add_executable(app src/main.cpp)
target_link_libraries(app PRIVATE Threads::Threads)
if(WIN32)
  target_link_libraries(app PRIVATE ws2_32)
endif()
