cmake_minimum_required(VERSION 3.16)
project(library_basic LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(library_basic src/main.cpp)
if(MSVC)
  target_compile_options(library_basic PRIVATE /W4)
else()
  target_compile_options(library_basic PRIVATE -Wall -Wextra -Wpedantic)
endif()
