#include <algorithm>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <vector>
using namespace std;
class TaxStrategy{public:virtual~TaxStrategy()=default;virtual double tax(double gross)const=0;};class ProgressiveTax:public TaxStrategy{public:double tax(double g)const override{if(g<=8000)return g*.05;if(g<=20000)return 400+(g-8000)*.12;return 1840+(g-20000)*.20;}};class Observer{public:virtual~Observer()=default;virtual void notify(const string&msg)=0;};class ConsoleObserver:public Observer{public:void notify(const string&msg)override{cout<<"[Notification] "<<msg<<'\n';ofstream("notifications.log",ios::app)<<msg<<'\n';}};
struct Leave{int id;string type,start,end,status="Pending";};class Employee{int id;string name,department,position;double baseSalary;map<string,double>allowances,deductions,attendance;vector<Leave>leaves;public:Employee(int i=0,string n="",string d="",string p="",double s=0):id(i),name(move(n)),department(move(d)),position(move(p)),baseSalary(s){}int getId()const{return id;}const string&getName()const{return name;}const string&getDept()const{return department;}void addAllowance(string n,double a){allowances[move(n)]+=a;}void addDeduction(string n,double a){deductions[move(n)]+=a;}void markAttendance(string date,double h){if(h<0||h>24)throw invalid_argument("invalid hours");attendance[move(date)]=h;}double overtime()const{double o=0;for(auto&[d,h]:attendance)if(h>8)o+=h-8;return o;}double gross()const{double a=0;for(auto&x:allowances)a+=x.second;return baseSalary+a+overtime()*(baseSalary/160.0)*1.5;}double fixedDeductions()const{double d=0;for(auto&x:deductions)d+=x.second;return d;}Leave&requestLeave(int lid,string t,string s,string e){leaves.push_back({lid,move(t),move(s),move(e),"Pending"});return leaves.back();}vector<Leave>&leaveList(){return leaves;}string data()const{return to_string(id)+"|"+name+"|"+department+"|"+position+"|"+to_string(baseSalary);}void show()const{cout<<id<<" | "<<name<<" | "<<department<<" | "<<position<<" | base "<<baseSalary<<'\n';}};
struct Payroll{int employeeId,month,year;double gross,tax,deductions,net,overtime;};class PayrollSystem{vector<Employee>employees;vector<Payroll>payrolls;int nextLeave=1;unique_ptr<TaxStrategy>tax=make_unique<ProgressiveTax>();shared_ptr<Observer>obs=make_shared<ConsoleObserver>();Employee*find(int id){for(auto&e:employees)if(e.getId()==id)return&e;return nullptr;}public:void load(){ifstream in("employees.txt");string l;while(getline(in,l)){stringstream s(l);string a,b,c,d,e;getline(s,a,'|');getline(s,b,'|');getline(s,c,'|');getline(s,d,'|');getline(s,e);if(!a.empty())employees.emplace_back(stoi(a),b,c,d,stod(e));}}void save()const{ofstream out("employees.txt");for(auto&e:employees)out<<e.data()<<'\n';ofstream p("payroll_history.txt");for(auto&x:payrolls)p<<x.employeeId<<'|'<<x.month<<'|'<<x.year<<'|'<<x.gross<<'|'<<x.tax<<'|'<<x.deductions<<'|'<<x.net<<'\n';}void add(){int id;double sal;string n,d,p;cout<<"Employee ID: ";cin>>id;if(find(id))return;cout<<"Name: ";cin>>ws;getline(cin,n);cout<<"Department: ";getline(cin,d);cout<<"Position: ";getline(cin,p);cout<<"Base salary: ";cin>>sal;employees.emplace_back(id,n,d,p,sal);}void attendance(){int id;string date;double h;cin>>id>>date>>h;if(auto*e=find(id))e->markAttendance(date,h);}void adjustment(){int id,c;double a;string n;cin>>id>>c;auto*e=find(id);if(!e)return;cin>>ws;getline(cin,n);cin>>a;if(c==1)e->addAllowance(n,a);else e->addDeduction(n,a);}void leave(){int id,c;cin>>id>>c;auto*e=find(id);if(!e)return;if(c==1){string t,s,en;cin>>t>>s>>en;e->requestLeave(nextLeave++,t,s,en);}else{int lid,ok;cin>>lid>>ok;for(auto&l:e->leaveList())if(l.id==lid){l.status=ok?"Approved":"Rejected";obs->notify("Leave "+to_string(l.id)+" "+l.status);}}}void process(){int id,m,y;cin>>id>>m>>y;auto*e=find(id);if(!e)return;double g=e->gross(),t=tax->tax(g),d=e->fixedDeductions(),n=g-t-d;payrolls.push_back({id,m,y,g,t,d,n,e->overtime()});cout<<fixed<<setprecision(2)<<"Gross "<<g<<" Tax "<<t<<" Deductions "<<d<<" Net "<<n<<'\n';ofstream("payslips.txt",ios::app)<<id<<'|'<<m<<'|'<<y<<'|'<<g<<'|'<<t<<'|'<<d<<'|'<<n<<'\n';obs->notify("Payroll processed for "+e->getName());}void report()const{map<string,double>dept;for(auto&p:payrolls)for(auto&e:employees)if(e.getId()==p.employeeId)dept[e.getDept()]+=p.net;for(auto&x:dept)cout<<x.first<<": "<<x.second<<'\n';}void list()const{for(auto&e:employees)e.show();}void run(){load();for(;;){cout<<"\nPayroll\n1 Add employee 2 Attendance 3 Allowance/deduction 4 Leave 5 Process payroll 6 Reports 7 List 0 Exit\n";int c;if(!(cin>>c)||c==0){save();break;}try{if(c==1)add();else if(c==2)attendance();else if(c==3)adjustment();else if(c==4)leave();else if(c==5)process();else if(c==6)report();else if(c==7)list();}catch(exception&e){cout<<e.what()<<'\n';}save();}}};int main(){PayrollSystem{}.run();}
