#include <algorithm>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
using namespace std;
class Book{string title,author,isbn;bool available=true;public:Book()=default;Book(string t,string a,string i,bool av=true):title(move(t)),author(move(a)),isbn(move(i)),available(av){}const string& getISBN()const{return isbn;}const string& getTitle()const{return title;}const string& getAuthor()const{return author;}bool isAvailable()const{return available;}bool borrow(){if(!available)return false;available=false;return true;}void giveBack(){available=true;}string data()const{return isbn+"|"+title+"|"+author+"|"+(available?"1":"0");}};
class Library{vector<Book> books;string file="books.txt";Book* findISBN(const string&i){for(auto&b:books)if(b.getISBN()==i)return &b;return nullptr;}public:void load(){ifstream in(file);string l;while(getline(in,l)){stringstream s(l);string i,t,a,v;getline(s,i,'|');getline(s,t,'|');getline(s,a,'|');getline(s,v);if(!i.empty())books.emplace_back(t,a,i,v!="0");}}void save()const{ofstream out(file);for(auto&b:books)out<<b.data()<<'\n';}void add(){string i,t,a;cout<<"ISBN: ";cin>>i;if(findISBN(i)){cout<<"Duplicate ISBN.\n";return;}cout<<"Title: ";cin>>ws;getline(cin,t);cout<<"Author: ";getline(cin,a);books.emplace_back(t,a,i);}void removeBook(){string i;cout<<"ISBN: ";cin>>i;books.erase(remove_if(books.begin(),books.end(),[&](auto&b){return b.getISBN()==i;}),books.end());}void search(){cout<<"1 ISBN 2 Title 3 Author: ";int c;cin>>c;string q;cout<<"Query: ";cin>>ws;getline(cin,q);for(auto&b:books){bool ok=(c==1&&b.getISBN()==q)||(c==2&&b.getTitle().find(q)!=string::npos)||(c==3&&b.getAuthor().find(q)!=string::npos);if(ok)cout<<b.getISBN()<<" | "<<b.getTitle()<<" | "<<b.getAuthor()<<" | "<<(b.isAvailable()?"Available":"Borrowed")<<'\n';}}void borrow(bool ret){string i;cout<<"ISBN: ";cin>>i;auto*b=findISBN(i);if(!b){cout<<"Not found.\n";return;}if(ret){b->giveBack();cout<<"Returned.\n";}else cout<<(b->borrow()?"Borrowed.\n":"Book is unavailable.\n");}void list()const{for(auto&b:books)cout<<b.getISBN()<<" | "<<b.getTitle()<<" | "<<b.getAuthor()<<" | "<<(b.isAvailable()?"Available":"Borrowed")<<'\n';}void run(){load();for(;;){cout<<"\nLibrary\n1 Add 2 Remove 3 Search 4 Borrow 5 Return 6 List 0 Exit\nChoice: ";int c;if(!(cin>>c))break;if(c==0){save();break;}if(c==1)add();else if(c==2)removeBook();else if(c==3)search();else if(c==4)borrow(false);else if(c==5)borrow(true);else if(c==6)list();save();}}};int main(){Library{}.run();}
